defaults: &defaults
  working_directory: ~/code
  docker:
    - image: circleci/android:api-26-alpha

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: gradle-{{ checksum "build.gradle" }}
      - run:
          name: Android SDK Licenses
          command: ci/android_sdk_licenses.sh
      - run:
          name: Dependencies
          command: ./gradlew --no-daemon --stacktrace dependencies
      - run:
          name: Unit Tests
          command: ./gradlew -q app:jacocoTestDebugUnitTestReport $TEST_FLAGS
      - store_test_results:
          path: "app/build/test-results/testDebugUnitTest"
      - run:
          name: Send coverage reports to CodeCov
          command: bash <(curl -s https://codecov.io/bash)
      - save_cache:
          key: gradle-{{ checksum "build.gradle" }}
          paths:
            - ~/.gradle