machine:
  environment:
    ENV: ci
    GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"'
    TERM: dumb
    TEST_FLAGS: "--configure-on-demand -PdisablePreDex"
    _JAVA_OPTIONS: "-Xmx3200m -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -XX:ParallelGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2"
  java:
    version: openjdk8

checkout:
  post:
    - git submodule sync
    - git submodule update --init

dependencies:
  pre:
    - mkdir -p $ANDROID_HOME/licenses
    - cp ${HOME}/${CIRCLE_PROJECT_REPONAME}/licenses/* $ANDROID_HOME/licenses/
    - echo y | android update sdk --no-ui --all --filter "tools,android-26,build-tools-26.0.2,platform-tools,extra-android-m2repository,extra-google-m2repository,extra-google-google_play_services"
test:
  override:
    - ./gradlew -q app:jacocoTestDebugUnitTestReport $TEST_FLAGS
  post:
    - cp -r app/build/test-results/testDebugUnitTest $CIRCLE_TEST_REPORTS || true
    - bash <(curl -s https://codecov.io/bash)
